### PR TITLE
PHPUnit 7 compatibility

### PR DESCRIPTION
**Pull request by robertmain**
Update the package to support PHP7 and PHPUnit 7

### CODE REVIEW

**Comment by robertmain** [comment]
Looks like the build failed on PHP 7.0 but passed on 7.1. The problem seems to be because composer can't put together a set of installable packages on 7.0.

Open to suggestions as to how to resolve this..

**Comment by jakubhomoly** [comment]
Update the `.travis.yml` file and remove php 7.0, since PHPUnit 7+ is only compatible with php > 7.1.

Theoretically, we should also be testing on 7.2 and 7.3, so you might as well add those while you're on it.

That should be it, thanks man!

If everything works, this will become version 4.0.0.

**Comment by robertmain** [comment]
Yeah, I wondered about that - but I wasn't sure about messing with it without talking to someone first. Thanks for the goahead. I'll do that just now...

**Comment by jakubhomoly** [comment]
my bad, 7.3 has not been released yet, what was I thinking.. sorry about that

**Comment by robertmain** [comment]
haha, was about to say. also - I need to fix the appveyor file too...lemme go do that.

**Comment by jakubhomoly** [comment]
LGTM, as soon as @HRcc gives the thumbs up too I'll merge it and update the readme as well. Thank you so much!

**Comment by robertmain** [comment]
Awesome, no probs :)

I like to write my tests like a list of specs. Your library is the closest thing I can find that facilitates that so that the passing tests read like an english sentence. I was bummed out when I couldn't use it with the newest version of PHPUnit so I decided to see if I could fix it :)

**Comment by robertmain** [comment]
<< Discussion Moved to #15 >>

**Comment by jakubhomoly** [comment]
@robertmain yeah open another issue and we can maybe brainstorm some ideas

**Review by rudowastaken — APPROVED** [review]

**Comment by rudowastaken** [comment]
Thank you @robertmain !

**Comment by robertmain** [comment]
my pleasure :)

**Pull request merged**
