### PR TITLE
Add PHPUnit 9 support

### LINKED ISSUE #21: Add PHPUnit 9 support
Hi there,

I'm using this dependency and was wondering if there are plans for PHPUnit 9 support?
It looks like in PHPUnit 9 the `PHPUnit\TextUI\ResultPrinter` class has been converted into an `interface` (check sebastianbergmann/phpunit#4024) and there is now a `PHPUnit\TextUI\DefaultResultPrinter`

So the fix to the issue would be simply to change this part: 

https://github.com/LimeDeck/phpunit-detailed-printer/blob/ae5ab59ae406c306b02a7cb8ec95dc99d5e6314c/src/Printer.php#L3-L11

to this:

```php
namespace LimeDeck\Testing;

use PHPUnit\Framework\Test;
use PHPUnit\Framework\Warning;
use PHPUnit\TextUI\DefaultResultPrinter;
use PHPUnit\Util\Test as UtilTest;
use PHPUnit\Framework\AssertionFailedError;

class Printer extends DefaultResultPrinter
{
...
}
```

### PR DESCRIPTION
**Pull request by steve-todorov**
This PR fixes #21 and adds support for PHPUnit 9. 

A few key notes:
1. `ResultPrinter` is now an interface and `DefaultResultPrinter` should be extended instead. (sebastianbergmann/phpunit#4024)
2. I've updated `phpunit` to 9 and fixed a few warnings.

### CODE REVIEW

**Comment by jakubhomoly** [comment]
@steve-todorov Thanks for your PR! I fixed the issue with CI not being hooked to PRs. There seems to be an issue with PHP 7.2 builds. Since apparently PHPUnit dropped support for PHP <= 7.2, I'll fix the expected versions in our TravisCI config file.

**Review by jakubhomoly — APPROVED** [review]
This looks good to me. Thank you!

**Comment by jakubhomoly** [comment]
I'm ready to merge this, unless you have any concerns @HRcc ?

**Comment by steve-todorov** [comment]
Thanks for fixing the build! I haven't updated the `README` but I assume you guys will do this before releasing. :)
Do you have any idea for when you will have time to merge and cut the next release? (after @HRcc has expressed his thoughts of course)

**Review by rudowastaken — APPROVED** [review]

**Comment by rudowastaken** [comment]
Looks good, thanks @steve-todorov!

**Comment by steve-todorov** [comment]
Awesome! Thanks for releasing! :)

**Pull request merged**
